### ISSUE TITLE
Blacklist wir ignoriert

### ISSUE THREAD

**Issue by mark77-DE** [Scrounger/ioBroker.linux-control#14]
Moin,

ich kontrolliere einen auf Linux basierenden SAT Receiver mit deinem Adapter. Im Forum steht zwar dass du nur Ubunut etc. unterstützt aber ich frage dennoch.

Wenn ich die Datenpunkte auf die Blacklist setzte, werden die Anfragen trotzdem an das Gerät gesendet, ist das so gewollt?
Oder sollten auch die Abfragen generell unterbunden werden? Falls nein, ließe sich das implementieren?

Meine Blacklist sieht so aus:
![2020-11-20_11h52_08](https://user-images.githubusercontent.com/31760710/99792398-55e93d80-2b27-11eb-946a-f576d1777e36.png)

Mein Log jedoch so:
`2020-11-20 11:47:08.994  - error:  linux-control.0 (11572) [distributionInfo] SAT-Receiver  (w.x.y.z:22): response error:  cat: can't open '/etc/os-release': No  such file or directory, stack: ResponseError: [distributionInfo]  SAT-Receiver (w.x.y.z:22): cat: can't open '/etc/os-release': No  such file or directory
at LinuxControl.sendCommand (/opt/iobroker/node_modules/iobroker.linux-control/main.js:856:26)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at LinuxControl.distributionInfo (/opt/iobroker/node_modules/iobroker.linux-control/main.js:553:21)
at LinuxControl.refreshHost (/opt/iobroker/node_modules/iobroker.linux-control/main.js:80:5)

2020-11-20 11:47:09.002  - error:  linux-control.0 (11572) [cmdAptUpdate] SAT-Receiver (w.x.y.z:22):  response error:  sh: apt-get: command not found, stack: ResponseError:  [cmdAptUpdate] SAT-Receiver (w.x.y.z:22): sh: apt-get: command not  found
at LinuxControl.sendCommand (/opt/iobroker/node_modules/iobroker.linux-control/main.js:856:26)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at LinuxControl.cmdAptUpdate (/opt/iobroker/node_modules/iobroker.linux-control/main.js:706:21)
at LinuxControl.updateInfos (/opt/iobroker/node_modules/iobroker.linux-control/main.js:609:5)
at LinuxControl.refreshHost (/opt/iobroker/node_modules/iobroker.linux-control/main.js:81:5)

2020-11-20 11:47:09.012  - error:  linux-control.0 (11572) [cmdPackageExist] SAT-Receiver  (w.x.y.z:22): response error:  sh: dpkg-query: command not found,  stack: ResponseError: [cmdPackageExist] SAT-Receiver (w.x.y.z:22):  sh: dpkg-query: command not found
at LinuxControl.sendCommand (/opt/iobroker/node_modules/iobroker.linux-control/main.js:856:26)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at LinuxControl.cmdPackageExist (/opt/iobroker/node_modules/iobroker.linux-control/main.js:675:20)
at LinuxControl.needrestart (/opt/iobroker/node_modules/iobroker.linux-control/main.js:406:10)
at LinuxControl.refreshHost (/opt/iobroker/node_modules/iobroker.linux-control/main.js:84:5)

2020-11-20 11:47:09.013  - warn:  linux-control.0 (11572) [needrestart] SAT-Receiver (w.x.y.z:22):  package 'needrestart' not installed. You must install 'needrestart' to  use this functions or deactivate the datapoints!

`

Gruß,
Mark

**Comment by Scrounger** [comment]
Um die Abfragen für eine node vollständig zu deaktivieren, musst du die parent node per drag and drop in die Blacklist ziehen.

![blacklist](https://user-images.githubusercontent.com/6370451/99910489-9ba43280-2cee-11eb-9c06-7a8ba1c18482.gif)
