### ISSUE TITLE
Fehlermeldungen wenn ein Gerät nicht erreichbar ist

### ISSUE THREAD

**Issue by xCruziX** [Scrounger/ioBroker.linux-control#18]
**Describe the bug**  
Wenn der Adapter zu einem System keine Verbindung aufbauen kann, werden Fehlermeldungen im Log angezeigt.

**To Reproduce**  
1. Starten des Adapters

**Expected behavior**  
Keine Fehlermeldung sondern nur die Änderung des Objekts linux-control.0.pc.info.is_online

**Screenshots & Logfiles**  

`2021-02-02 22:05:02.093 - info: dwd.0 (30427) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- `
`2021-02-02 22:05:02.604 - info: host.iobroker instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)`
`2021-02-02 22:05:13.933 - error: linux-control.0 (30062) [getConnection] Could not establish a connection to 'pc' (192.168.2.50:22)!`
`2021-02-02 22:05:13.935 - error: linux-control.0 (30062) [getConnection] error: Timed out while waiting for handshake, stack: Error: Timed out while waiting for handshake`
`at Timeout._onTimeout (/opt/iobroker/node_modules/ssh2/lib/client.js:695:19)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)`

**Versions:**  
 - Adapter version: 1.1.2
 - JS-Controller version: 3.2.13
 - Node version: 12.20.0
 - Operating system: Ubuntu 20 LXC

**Comment by xCruziX** [comment]
Es lag daran, dass ich ein Dualboot System habe und beide Systeme die gleiche IP. Also hat der Adapter einen Ping auf den vermeintlichen Linux Rechner gemacht, welcher von meinem Windows System beantwortet wurde, danach wurde der ssh Zugriff versucht und ist auf einen Fehler gelaufen.
