### ISSUE TITLE
Js-controller 4.0.4: warn messages in log when starting the Adapter

### ISSUE THREAD

**Issue by MK-66** [Scrounger/ioBroker.linux-control#36]
The following warn messages appear in the iobroker log when starting the adapter linux control v1.1.4 with the new js-controllers 4.0.4:

Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"
This object will not be created in future versions. Please report this to the developer.

**Comment by wendy2702** [comment]
Running JS 4.0.21 i gut these messages:


`
<html><body>


linux-control.0 | 2022-03-15 14:46:53.056 | warn | State "linux-control.0.VIS-EG.services.fwupd.description" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
linux-control.0 | 2022-03-15 14:46:53.054 | warn | State "linux-control.0.VIS-EG.services.fwupd.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:46:53.052 | warn | State "linux-control.0.VIS-EG.services.fwupd.active" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:46:53.008 | warn | State "linux-control.0.VIS-EG.services.fwupd.load" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:41:39.572 | warn | State "linux-control.0.VIS-EG.services.fwupd.description" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:41:39.570 | warn | State "linux-control.0.VIS-EG.services.fwupd.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:41:39.568 | warn | State "linux-control.0.VIS-EG.services.fwupd.active" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:41:39.526 | warn | State "linux-control.0.VIS-EG.services.fwupd.load" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:36:26.197 | warn | State "linux-control.0.VIS-EG.services.fwupd.description" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:36:26.195 | warn | State "linux-control.0.VIS-EG.services.fwupd.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:36:26.192 | warn | State "linux-control.0.VIS-EG.services.fwupd.active" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:36:26.149 | warn | State "linux-control.0.VIS-EG.services.fwupd.load" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:31:12.376 | warn | State "linux-control.0.VIS-EG.services.fwupd.description" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:31:12.334 | warn | State "linux-control.0.VIS-EG.services.fwupd.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2022-03-15 14:31:12.319 | warn | State "linux-control.0.VIS-EG.services.fwupd.active" has no existing object, this might lead to an error in future versions


</body>
</html>
`

**Comment by Scrounger** [comment]
Please delete these objects and restart the adapter. If's still showing the message, post the logs

**Comment by mickym2** [comment]
In my case this does not change anything. 

1. I installed the adapter a few weeks ago, so all objects were created new by the adapter and i am using js adapter 5.7 as long it was in stable repository. So all objects were created under a JS adapter > version 4.04
2. I deleted the object and restarted the adapter. Object was recreated with the same error:

<html>
<body>


linux-control.0 | 2022-08-14 12:51:50.503 | info | successful received data from MWIPv6GW (192.168.178.200:22)
-- | -- | -- | --
linux-control.0 | 2022-08-14 12:51:43.978 | info | successful received data from MWHome (localhost:22)
linux-control.0 | 2022-08-14 12:51:30.428 | info | getting data from MWHome (localhost:22, Adapter start)
linux-control.0 | 2022-08-14 12:51:30.426 | info | getting data from MWIPv6GW (192.168.178.200:22, Adapter start)
linux-control.0 | 2022-08-14 12:51:30.400 | warn | This object will not be created in future versions. Please report this to the developer.
linux-control.0 | 2022-08-14 12:51:30.398 | warn | Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"
linux-control.0 | 2022-08-14 12:51:30.277 | info | starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.linux-control, node: v16.16.0, js-controller: 4.0.23
linux-control.0 | 2022-08-14 12:51:30.221 | warn | This object will not be created in future versions. Please report this to the developer.
linux-control.0 | 2022-08-14 12:51:30.218 | warn | Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"
linux-control.0 | 2022-08-14 12:51:30.204 | warn | This object will not be created in future versions. Please report this to the developer.
linux-control.0 | 2022-08-14 12:51:30.199 | warn | Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"
host.MWHome2 | 2022-08-14 12:51:25.183 | info | instance system.adapter.linux-control.0 started with pid 267871
host.MWHome2 | 2022-08-14 12:51:22.203 | info | instance system.adapter.linux-control.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
linux-control.0 | 2022-08-14 12:51:21.525 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
linux-control.0 | 2022-08-14 12:51:21.524 | info | terminating
linux-control.0 | 2022-08-14 12:51:21.523 | info | cleaned everything up...
linux-control.0 | 2022-08-14 12:51:21.521 | info | Got terminate signal TERMINATE_YOURSELF
host.MWHome2 | 2022-08-14 12:51:21.522 | info | stopInstance system.adapter.linux-control.0 send kill signal
host.MWHome2 | 2022-08-14 12:51:21.434 | info | stopInstance system.adapter.linux-control.0 (force=false, process=true)


</body>
</html>

**Comment by wendy2702** [comment]
Instanz stopped
all Objects deleted
Instanz started

Log

```
2022-08-15 10:09:34.949  - info: host.iobroker "system.adapter.linux-control.0" enabled
2022-08-15 10:09:35.256  - info: host.iobroker instance system.adapter.linux-control.0 started with pid 20864
2022-08-15 10:09:36.578  - warn: linux-control.0 (20864) Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2022-08-15 10:09:36.579  - warn: linux-control.0 (20864) This object will not be created in future versions. Please report this to the developer.
2022-08-15 10:09:36.584  - warn: linux-control.0 (20864) Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2022-08-15 10:09:36.584  - warn: linux-control.0 (20864) This object will not be created in future versions. Please report this to the developer.
2022-08-15 10:09:36.590  - info: linux-control.0 (20864) starting. Version 1.1.5 in /opt/iobroker/node_modules/iobroker.linux-control, node: v16.16.0, js-controller: 4.0.23
2022-08-15 10:09:36.617  - warn: linux-control.0 (20864) Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2022-08-15 10:09:36.617  - warn: linux-control.0 (20864) This object will not be created in future versions. Please report this to the developer.
2022-08-15 10:09:36.623  - info: linux-control.0 (20864) getting data from VIS-OG (192.168.178.215:22, Adapter start)
2022-08-15 10:09:36.626  - info: linux-control.0 (20864) getting data from VIS-EG (192.168.178.216:22, Adapter start)
2022-08-15 10:09:57.108  - warn: linux-control.0 (20864) Used invalid characters: linux-control.0.VIS-OG.services.systemd-fsck@dev-disk-by\x2duuid-F213\x2dEECC.running changed to linux-control.0.VIS-OG.services.systemd-fsck@dev-disk-by_x2duuid-F213_x2dEECC.running
2022-08-15 10:09:57.109  - warn: linux-control.0 (20864) State "linux-control.0.VIS-OG.services.systemd-fsck@dev-disk-by_x2duuid-F213_x2dEECC.running" has no existing object, this might lead to an error in future versions
2022-08-15 10:09:59.018  - warn: linux-control.0 (20864) Used invalid characters: linux-control.0.VIS-EG.services.systemd-fsck@dev-disk-by\x2duuid-BDCB\x2dE7C4.running changed to linux-control.0.VIS-EG.services.systemd-fsck@dev-disk-by_x2duuid-BDCB_x2dE7C4.running
2022-08-15 10:09:59.036  - warn: linux-control.0 (20864) State "linux-control.0.VIS-EG.services.systemd-fsck@dev-disk-by_x2duuid-BDCB_x2dE7C4.running" has no existing object, this might lead to an error in future versions
2022-08-15 10:10:03.400  - info: linux-control.0 (20864) successful received data from VIS-OG (192.168.178.215:22)
2022-08-15 10:10:04.823  - info: linux-control.0 (20864) successful received data from VIS-EG (192.168.178.216:22)
`

**Comment by copystring** [comment]
Hi.

I Updated to 1.1.6 and still have this error.

```
2022-09-10 17:44:22.938 - error: linux-control.0 (89662) [servicesInfo] iobroker (iobroker:22): error: Invalid ID: linux-control.0.iobroker.services.*.load, stack: Error: Invalid ID: linux-control.0.iobroker.services.*.load
at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17)
at ObjectsInRedisClient._setObject (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:2980:26)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:3211:29)
at processImmediate (node:internal/timers:468:21)
2022-09-10 17:44:23.158 - info: linux-control.0 (89662) successful received data from iobroker (iobroker:22)
2022-09-10 17:44:23.675 - error: linux-control.0 (89662) [servicesInfo] storj (storj:22): error: Invalid ID: linux-control.0.storj.services.*.load, stack: Error: Invalid ID: linux-control.0.storj.services.*.load
at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17)
at ObjectsInRedisClient._setObject (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:2980:26)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:3211:29)
at processImmediate (node:internal/timers:468:21)
2022-09-10 17:44:23.740 - info: linux-control.0 (89662) successful received data from storj (storj:22)
```

**Comment by copystring** [comment]
@Scrounger 
Checked the logs. Could it be that services with a dot or a minus in the name could cause problems?

![image](https://user-images.githubusercontent.com/1298861/192089204-f39c123b-da4b-4ed6-91bc-fb82521de33c.png)

**Comment by rebel1985** [comment]
i have also the problems,
restart or delete the datapoint has no changes.

`Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"`

**Comment by dbweb-ch** [comment]
Same here. Fresh installed adapter v1.1.5
`Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"`

**Comment by Berchemer** [comment]
> Same here. Fresh installed adapter v1.1.5 `Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"`

Same here:

- iob js-controller v5.0.19
- Adapter v1.1.5
- complete Object-Tree of linux-control was deleted before and adapter was restartet.

```
linux-control.0 | 2024-05-24 08:29:16.625 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
linux-control.0 | 2024-05-24 08:29:16.625 | warn | Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"

```
