### ISSUE TITLE
keine Abfrage von Grafanaversion möglich

### ISSUE THREAD

**Issue by djmarc75** [Scrounger/ioBroker.linux-control#43]
Tag,
habe heute festgestellt dass folgende Befehle nicht funktionieren:
`grafana-cli -v und 
grafana-server -v`
Ich kann die Befehle ohne Probleme per ssh und auch in Blockly mit einem exec-Block aufrufen und bekomme die korrekten Ergebnisse.
Wenn ich aber einen dieser Befehle im Adapter eingebe dann kommt folgendes im LOG:
`<html><body>

  | [userCommandExecute]  RPI-Tools (192.168.178.4:22, id: grafana, description: Grafana):  response error:  bash: line 1: grafana-cli: command not found, stack:  ResponseError: [userCommandExecute] RPI-Tools (192.168.178.4:22, id:  grafana, description: Grafana): bash: line 1: grafana-cli: command not  found     at LinuxControl.sendCommand  (/opt/iobroker/node_modules/iobroker.linux-control/main.js:886:26)     at processTicksAndRejections  (node:internal/process/task_queues:96:5)     at LinuxControl.userCommandExecute  (/opt/iobroker/node_modules/iobroker.linux-control/main.js:249:21)     at LinuxControl.userCommand  (/opt/iobroker/node_modules/iobroker.linux-control/main.js:194:9)     at LinuxControl.refreshHost  (/opt/iobroker/node_modules/iobroker.linux-control/main.js:85:5)
-- | --

</body>
</html>`

Wäre da eine Korrektur machbar?
Vielen Dank und Grüße

**Comment by djmarc75** [comment]
Dank des Forums konnte ich die Version mit
`sudo -S grafana-cli -v`
abrufen.... 
closed
