### ISSUE TITLE
adapter bootloop after js controller update

### ISSUE THREAD

**Issue by Holger76** [Scrounger/ioBroker.linux-control#53]
Hello,

the following problem occurs after updating to the current stable js-controller 5.0.12: the adapter linux-control (v: 1.1.5) cannot be started and acknowledges with the message 'Boot loop'.

`<html><body>

host.ioB | 2023-09-15 23:55:22.790 | info | Do not restart adapter system.adapter.linux-control.0 because disabled or deleted
-- | -- | -- | --
host.ioB | 2023-09-15 23:55:22.789 | error | instance system.adapter.linux-control.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
linux-control.0 | 2023-09-15 23:55:22.228 | warn | Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
linux-control.0 | 2023-09-15 23:55:22.180 | error | adapter disabled
host.ioB | 2023-09-15 23:55:03.056 | info | "system.adapter.linux-control.0" disabled
host.ioB | 2023-09-15 23:54:51.338 | info | Restart adapter system.adapter.linux-control.0 because enabled
host.ioB | 2023-09-15 23:54:51.338 | error | instance system.adapter.linux-control.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[5]:     at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[5]:     at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[5]: ReplyError: Error The pattern "linux-control.0.OMV.services.●.stop" is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[5]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]:     at StateRedisClient.subscribe  (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:1108:27)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]:     at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]: Error: The pattern "io.linux-control.0.OMV.services.●.start" is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]: ReplyError: Error The pattern "linux-control.0.OMV.services.●.restart" is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: ReplyError: Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b3793be5a.stop"  is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: ReplyError: Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b3793be5a.start"  is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: ReplyError: Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-28aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b3793be5a.restart"  is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: ReplyError: Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool.stop"  is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[4]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]:     at StateRedisClient.subscribe  (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:1108:27)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]:     at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: Error: The pattern  "io.linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool.start"  is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[4]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[3]:     at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[3]:     at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[3]: ReplyError: Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool8T.restart"  is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.338 | error | Caught  by controller[3]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[2]:     at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioB | 2023-09-15 23:54:51.338 | error | Caught by controller[2]:     at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioB | 2023-09-15 23:54:51.337 | error | Caught by controller[2]: ReplyError: Error The pattern "linux-control.0.PBS.services.●.stop" is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.337 | error | Caught  by controller[2]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
host.ioB | 2023-09-15 23:54:51.337 | error | Caught by controller[1]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.ioB | 2023-09-15 23:54:51.337 | error | Caught  by controller[1]:     at StateRedisClient.subscribe  (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:1108:27)
host.ioB | 2023-09-15 23:54:51.337 | error | Caught  by controller[1]:     at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)
host.ioB | 2023-09-15 23:54:51.337 | error | Caught by controller[1]: Error: The pattern "io.linux-control.0.PBS.services.●.start" is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.337 | error | Caught  by controller[1]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
host.ioB | 2023-09-15 23:54:51.337 | error | Caught by controller[0]:     at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioB | 2023-09-15 23:54:51.337 | error | Caught by controller[0]:     at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioB | 2023-09-15 23:54:51.337 | error | Caught by controller[0]: ReplyError: Error The pattern "linux-control.0.PBS.services.●.restart" is not a valid ID pattern
host.ioB | 2023-09-15 23:54:51.337 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
linux-control.0 | 2023-09-15 23:54:51.274 | info | terminating
linux-control.0 | 2023-09-15 23:54:50.860 | error | Error The pattern "linux-control.0.OMV.services.●.stop" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.860 | error | ReplyError:  Error The pattern "linux-control.0.OMV.services.●.stop" is not a valid  ID pattern    at parseError  (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)    at  parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 | 2023-09-15 23:54:50.859 | error | unhandled promise rejection: Error The pattern "linux-control.0.OMV.services.●.stop" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.859 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
linux-control.0 | 2023-09-15 23:54:50.852 | error | The pattern "io.linux-control.0.OMV.services.●.start" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.852 | error | Error:  The pattern "io.linux-control.0.OMV.services.●.start" is not a valid ID  pattern    at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)     at StateRedisClient.subscribe  (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:1108:27)     at processTicksAndRejections  (node:internal/process/task_queues:95:5)
linux-control.0 | 2023-09-15 23:54:50.852 | error | unhandled promise rejection: The pattern "io.linux-control.0.OMV.services.●.start" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.851 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
linux-control.0 | 2023-09-15 23:54:50.851 | error | Error The pattern "linux-control.0.OMV.services.●.restart" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.851 | error | ReplyError:  Error The pattern "linux-control.0.OMV.services.●.restart" is not a  valid ID pattern    at parseError  (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)    at  parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 | 2023-09-15 23:54:50.851 | error | unhandled promise rejection: Error The pattern "linux-control.0.OMV.services.●.restart" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.851 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
linux-control.0 | 2023-09-15 23:54:50.850 | error | Error  The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b3793be5a.stop"  is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.850 | error | ReplyError:  Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x210b3793be5a.stop"  is not a valid ID pattern    at parseError  (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)    at  parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 | 2023-09-15 23:54:50.850 | error | unhandled  promise rejection: Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b3793be5a.stop"  is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.850 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
linux-control.0 | 2023-09-15 23:54:50.850 | error | Error  The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b3793be5a.start"  is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.850 | error | ReplyError:  Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd1093be5a.start"  is not a valid ID pattern    at parseError  (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)    at  parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 | 2023-09-15 23:54:50.850 | error | unhandled  promise rejection: Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b3793be5a.start"  is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.849 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
linux-control.0 | 2023-09-15 23:54:50.849 | error | Error  The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b3793be5a.restart"  is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.849 | error | ReplyError:  Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b379e5a.restart"  is not a valid ID pattern    at parseError  (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)    at  parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 | 2023-09-15 23:54:50.849 | error | unhandled  promise rejection: Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b3793be5a.restart"  is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.849 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
linux-control.0 | 2023-09-15 23:54:50.848 | error | Error The pattern "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool8T.stop" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.848 | error | ReplyError:  Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool8T.stop"  is not a valid ID pattern    at parseError  (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)    at  parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 | 2023-09-15 23:54:50.848 | error | unhandled  promise rejection: Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool8T.stop"  is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.848 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
linux-control.0 | 2023-09-15 23:54:50.847 | error | The pattern "io.linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool8T.start" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.847 | error | Error:  The pattern  "io.linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool8T.start"  is not a valid ID pattern    at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)     at StateRedisClient.subscribe  (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:1108:27)     at processTicksAndRejections  (node:internal/process/task_queues:95:5)
linux-control.0 | 2023-09-15 23:54:50.847 | error | unhandled  promise rejection: The pattern  "io.linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool8T.start"  is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.847 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
linux-control.0 | 2023-09-15 23:54:50.846 | error | Error The pattern "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool8T.restart" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.846 | error | ReplyError:  Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool8T.restart"  is not a valid ID pattern    at parseError  (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)    at  parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 | 2023-09-15 23:54:50.846 | error | unhandled  promise rejection: Error The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool8T.restart"  is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.845 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
host.ioB-Server | 2023-09-15 23:54:50.842 | warn | States  127.0.0.1:36038 Error from InMemDB: Error: The pattern  "linux-control.0.OMV.services.●.stop" is not a valid ID pattern    at  Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)     at StatesInMemoryServer.handleSubscribe  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/inMemFileDB.ts:324:59)     at StatesInMemoryServer._subscribeForClient  (/opt/iobroker/node_modules/@iobroker/db-states-file/src/lib/states/statesInMemFileDB.js:258:14)     at RedisHandler.<anonymous>  (/opt/iobroker/node_modules/@iobroker/db-states-jsonl/src/lib/states/statesInMemServerRedis.js:395:26)     at RedisHandler.emit (node:events:514:28)    at RedisHandler.emit  (node:domain:489:12)    at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)     at processImmediate (node:internal/timers:476:21)
host.ioB-Server | 2023-09-15 23:54:50.842 | warn | States  127.0.0.1:36038 Error from InMemDB: Error: The pattern  "linux-control.0.OMV.services.●.restart" is not a valid ID pattern    at  Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)     at StatesInMemoryServer.handleSubscribe  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/inMemFileDB.ts:324:59)     at StatesInMemoryServer._subscribeForClient  (/opt/iobroker/node_modules/@iobroker/db-states-file/src/lib/states/statesInMemFileDB.js:258:14)     at RedisHandler.<anonymous>  (/opt/iobroker/node_modules/@iobroker/db-states-jsonl/src/lib/states/statesInMemServerRedis.js:395:26)     at RedisHandler.emit (node:events:514:28)    at RedisHandler.emit  (node:domain:489:12)    at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)     at processImmediate (node:internal/timers:476:21)
host.ioB-Server | 2023-09-15 23:54:50.839 | warn | States  127.0.0.1:36038 Error from InMemDB: Error: The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b3793be5a.stop"  is not a valid ID pattern    at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)     at StatesInMemoryServer.handleSubscribe  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/inMemFileDB.ts:324:59)     at StatesInMemoryServer._subscribeForClient  (/opt/iobroker/node_modules/@iobroker/db-states-file/src/lib/states/statesInMemFileDB.js:258:14)     at RedisHandler.<anonymous>  (/opt/iobroker/node_modules/@iobroker/db-states-jsonl/src/lib/states/statesInMemServerRedis.js:395:26)     at RedisHandler.emit (node:events:514:28)    at RedisHandler.emit  (node:domain:489:12)    at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)     at processImmediate (node:internal/timers:476:21)
host.ioB-Server | 2023-09-15 23:54:50.839 | warn | States  127.0.0.1:36038 Error from InMemDB: Error: The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9b7\x2dd10b3793be5a.start"  is not a valid ID pattern    at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)     at StatesInMemoryServer.handleSubscribe  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/inMemFileDB.ts:324:59)     at StatesInMemoryServer._subscribeForClient  (/opt/iobroker/node_modules/@iobroker/db-states-file/src/lib/states/statesInMemFileDB.js:258:14)     at RedisHandler.<anonymous>  (/opt/iobroker/node_modules/@iobroker/db-states-jsonl/src/lib/states/statesInMemServerRedis.js:395:26)     at RedisHandler.emit (node:events:514:28)    at RedisHandler.emit  (node:domain:489:12)    at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)     at processImmediate (node:internal/timers:476:21)
host.ioB-Server | 2023-09-15 23:54:50.838 | warn | States  127.0.0.1:36038 Error from InMemDB: Error: The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2duuid-2b18aa54\x2d0083\x2d4b4f\x2da9\x2dd10b3793be5a.restart"  is not a valid ID pattern    at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)     at StatesInMemoryServer.handleSubscribe  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/inMemFileDB.ts:324:59)     at StatesInMemoryServer._subscribeForClient  (/opt/iobroker/node_modules/@iobroker/db-states-file/src/lib/states/statesInMemFileDB.js:258:14)     at RedisHandler.<anonymous>  (/opt/iobroker/node_modules/@iobroker/db-states-jsonl/src/lib/states/statesInMemServerRedis.js:395:26)     at RedisHandler.emit (node:events:514:28)    at RedisHandler.emit  (node:domain:489:12)    at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)     at processImmediate (node:internal/timers:476:21)
host.ioB-Server | 2023-09-15 23:54:50.838 | warn | States  127.0.0.1:36038 Error from InMemDB: Error: The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool.stop"  is not a valid ID pattern    at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)     at StatesInMemoryServer.handleSubscribe  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/inMemFileDB.ts:324:59)     at StatesInMemoryServer._subscribeForClient  (/opt/iobroker/node_modules/@iobroker/db-states-file/src/lib/states/statesInMemFileDB.js:258:14)     at RedisHandler.<anonymous>  (/opt/iobroker/node_modules/@iobroker/db-states-jsonl/src/lib/states/statesInMemServerRedis.js:395:26)     at RedisHandler.emit (node:events:514:28)    at RedisHandler.emit  (node:domain:489:12)    at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)     at processImmediate (node:internal/timers:476:21)
host.ioB-Server | 2023-09-15 23:54:50.837 | warn | States  127.0.0.1:36038 Error from InMemDB: Error: The pattern  "linux-control.0.OMV.services.systemd-fsck@dev-disk-by\x2dlabel-bigpool8T.restart"  is not a valid ID pattern    at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)     at StatesInMemoryServer.handleSubscribe  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/inMemFileDB.ts:324:59)     at StatesInMemoryServer._subscribeForClient  (/opt/iobroker/node_modules/@iobroker/db-states-file/src/lib/states/statesInMemFileDB.js:258:14)     at RedisHandler.<anonymous>  (/opt/iobroker/node_modules/@iobroker/db-states-jsonl/src/lib/states/statesInMemServerRedis.js:395:26)     at RedisHandler.emit (node:events:514:28)    at RedisHandler.emit  (node:domain:489:12)    at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)     at processImmediate (node:internal/timers:476:21)
linux-control.0 | 2023-09-15 23:54:50.773 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
linux-control.0 | 2023-09-15 23:54:50.773 | info | terminating
linux-control.0 | 2023-09-15 23:54:50.772 | info | cleaned everything up...
linux-control.0 | 2023-09-15 23:54:50.768 | error | Error The pattern "linux-control.0.PBS.services.●.stop" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.768 | error | ReplyError:  Error The pattern "linux-control.0.PBS.services.●.stop" is not a valid  ID pattern    at parseError  (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)    at  parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 | 2023-09-15 23:54:50.768 | error | unhandled promise rejection: Error The pattern "linux-control.0.PBS.services.●.stop" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.768 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
linux-control.0 | 2023-09-15 23:54:50.767 | error | The pattern "io.linux-control.0.PBS.services.●.start" is not a valid ID pattern
linux-control.0 | 2023-09-15 23:54:50.767 | error | Error:  The pattern "io.linux-control.0.PBS.services.●.start" is not a valid ID  pattern    at Object.pattern2RegEx  (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)     at StateRedisClient.subscribe  (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:1108:27)     at processTicksAndRejections  (node:internal/process/task_queues:95:5)
linux-control.0 | 2023-09-15 23:54:50.722 | error | unhandled promise rejection: The pattern "io.linux-control.0.PBS.services.●.start" is not a valid ID pattern

</body>
</html>`

**Comment by Holger76** [comment]
after deleting the datapoints the problem is solved.
