### ISSUE TITLE
Error nach JS-C 5.0.12 Update

### ISSUE THREAD

**Issue by Negalein** [Scrounger/ioBroker.linux-control#55]
nach JS-Controllerupdate von 4.x.x auf 5.0.12
stoppt Linux-Controll mit Fehler.

Linux-Control: 1.1.5
Admin: 6.10.2
NodeJS: v18.17.1
NPM: 9.6.7

```
host.ioBroker
2023-09-24 20:14:29.178	error	instance system.adapter.linux-control.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[2]: at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[2]: at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[2]: ReplyError: Error The pattern "linux-control.0.Proxmox.services.●.stop" is not a valid ID pattern
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[2]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[1]: at StateRedisClient.subscribe (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:1108:27)
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[1]: at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[1]: Error: The pattern "io.linux-control.0.Proxmox.services.●.start" is not a valid ID pattern
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[0]: at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[0]: at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[0]: ReplyError: Error The pattern "linux-control.0.Proxmox.services.●.restart" is not a valid ID pattern
host.ioBroker
2023-09-24 20:14:29.178	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

linux-control.0
2023-09-24 20:14:28.991	error	[servicesInfo] Proxmox (10.0.1.201:22): error: DB closed, stack: Error: DB closed at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24) at Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25) at StateRedisClient.setState (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:726:40) at LinuxControl._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7711:34)

linux-control.0
2023-09-24 20:14:28.552	error	Error The pattern "linux-control.0.Proxmox.services.●.stop" is not a valid ID pattern

linux-control.0
2023-09-24 20:14:28.552	error	ReplyError: Error The pattern "linux-control.0.Proxmox.services.●.stop" is not a valid ID pattern at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)

linux-control.0
2023-09-24 20:14:28.552	error	unhandled promise rejection: Error The pattern "linux-control.0.Proxmox.services.●.stop" is not a valid ID pattern

linux-control.0
2023-09-24 20:14:28.552	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

linux-control.0
2023-09-24 20:14:28.538	error	The pattern "io.linux-control.0.Proxmox.services.●.start" is not a valid ID pattern

linux-control.0
2023-09-24 20:14:28.538	error	Error: The pattern "io.linux-control.0.Proxmox.services.●.start" is not a valid ID pattern at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15) at StateRedisClient.subscribe (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:1108:27) at processTicksAndRejections (node:internal/process/task_queues:95:5)

linux-control.0
2023-09-24 20:14:28.458	error	unhandled promise rejection: The pattern "io.linux-control.0.Proxmox.services.●.start" is not a valid ID pattern

linux-control.0
2023-09-24 20:14:28.458	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

linux-control.0
2023-09-24 20:14:28.367	error	Error The pattern "linux-control.0.Proxmox.services.●.restart" is not a valid ID pattern

linux-control.0
2023-09-24 20:14:28.366	error	ReplyError: Error The pattern "linux-control.0.Proxmox.services.●.restart" is not a valid ID pattern at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)

linux-control.0
2023-09-24 20:14:28.365	error	unhandled promise rejection: Error The pattern "linux-control.0.Proxmox.services.●.restart" is not a valid ID pattern

linux-control.0
2023-09-24 20:14:28.365	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

**Comment by copystring** [comment]
https://github.com/Scrounger/ioBroker.linux-control/pull/57 would fix your issue.

**Comment by Negalein** [comment]
> #57 would fix your issue.

Danke, dann wird @Scrounger es hoffentlich sehr bald übernehmen?
Oder kann ich es selber lösen?

**Comment by copystring** [comment]
Bis das behoben und in einem neuen Release verpackt wurde, kannst du meinen Fork über https://github.com/copystring/ioBroker.linux-control installieren und testen.

**Comment by Negalein** [comment]
> Bis das behoben und in einem neuen Release verpackt wurde, kannst du meinen Fork über https://github.com/copystring/ioBroker.linux-control installieren und testen.

Sorry für die späte Rückmeldung.

Brachte leider keine Verbesserung

```
host.ioBroker 2023-10-10 19:14:42.336	error	instance system.adapter.linux-control.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[2]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[2]: at StateRedisClient.subscribe (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:1108:27)
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[2]: at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[2]: Error: The pattern "io.linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.stop" is not a valid ID pattern
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[2]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[1]: at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[1]: at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[1]: ReplyError: Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.start" is not a valid ID pattern
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[0]: at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[0]: at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[0]: ReplyError: Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.restart" is not a valid ID pattern
host.ioBroker 2023-10-10 19:14:42.336	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
linux-control.0 2023-10-10 19:14:41.721	error	The pattern "io.linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.stop" is not a valid ID pattern
linux-control.0 2023-10-10 19:14:41.721	error	Error: The pattern "io.linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.stop" is not a valid ID pattern at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15) at StateRedisClient.subscribe (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:1108:27) at processTicksAndRejections (node:internal/process/task_queues:95:5)
linux-control.0 2023-10-10 19:14:41.654	error	unhandled promise rejection: The pattern "io.linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.stop" is not a valid ID pattern
linux-control.0 2023-10-10 19:14:41.654	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
linux-control.0 2023-10-10 19:14:41.644	error	Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.start" is not a valid ID pattern
linux-control.0 2023-10-10 19:14:41.644	error	ReplyError: Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.start" is not a valid ID pattern at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 2023-10-10 19:14:41.644	error	unhandled promise rejection: Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.start" is not a valid ID pattern
linux-control.0 2023-10-10 19:14:41.644	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
linux-control.0 2023-10-10 19:14:41.556	error	Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.restart" is not a valid ID pattern
linux-control.0 2023-10-10 19:14:41.556	error	ReplyError: Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.restart" is not a valid ID pattern at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 2023-10-10 19:14:41.554	error	unhandled promise rejection: Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.restart" is not a valid ID pattern
linux-control.0 2023-10-10 19:14:41.554	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

**Comment by Negalein** [comment]
> Bis das behoben und in einem neuen Release verpackt wurde, kannst du meinen Fork über https://github.com/copystring/ioBroker.linux-control installieren und testen.

konntest du im Log oben was sehen?

**Comment by Negalein** [comment]
@Scrounger 

mit JS-Controller 5.0.15 noch immer die Probleme.

```
linux-control.0 2023-11-05 15:21:15.201	error	adapter disabled
linux-control.0 2023-11-05 15:20:43.666	error	[needrestart] Proxmox (10.0.1.201:22): error: Cannot find view "system", stack: Error: Cannot find view "system" at ObjectsInRedisClient._getObjectView (/opt/iobroker/node_modules/@iobroker/db-objects-redis/src/lib/objects/objectsInRedisClient.ts:4317:19) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-objects-redis/src/lib/objects/objectsInRedisClient.ts:4392:37)
linux-control.0 2023-11-05 15:20:43.612	error	Cannot find view "system" for search "state" : Connection is closed.
linux-control.0 2023-11-05 15:20:43.610	error	[servicesInfo] Proxmox (10.0.1.201:22): error: Connection is closed., stack: Error: Connection is closed. at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:632:26) at Socket.emit (node:events:517:28) at Socket.emit (node:domain:489:12) at TCP.<anonymous> (node:net:350:12)
linux-control.0 2023-11-05 15:20:43.250	error	The pattern "io.linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.stop" is not a valid ID pattern
linux-control.0 2023-11-05 15:20:43.250	error	Error: The pattern "io.linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.stop" is not a valid ID pattern at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2467:15) at StateRedisClient.subscribe (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:1108:27) at processTicksAndRejections (node:internal/process/task_queues:95:5)
linux-control.0 2023-11-05 15:20:43.184	error	unhandled promise rejection: The pattern "io.linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.stop" is not a valid ID pattern
linux-control.0 2023-11-05 15:20:43.184	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
linux-control.0 2023-11-05 15:20:43.181	warn	Used invalid characters: linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.stop changed to linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by_x2duuid-9C29_x2d4D7D.stop
linux-control.0 2023-11-05 15:20:43.177	error	Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.start" is not a valid ID pattern
linux-control.0 2023-11-05 15:20:43.177	error	ReplyError: Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.start" is not a valid ID pattern at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 2023-11-05 15:20:43.177	error	unhandled promise rejection: Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.start" is not a valid ID pattern
linux-control.0 2023-11-05 15:20:43.177	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
linux-control.0 2023-11-05 15:20:43.098	warn	Used invalid characters: linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.start changed to linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by_x2duuid-9C29_x2d4D7D.start
linux-control.0 2023-11-05 15:20:43.098	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
linux-control.0 2023-11-05 15:20:43.088	error	Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.restart" is not a valid ID pattern
linux-control.0 2023-11-05 15:20:43.088	error	ReplyError: Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.restart" is not a valid ID pattern at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
linux-control.0 2023-11-05 15:20:43.086	error	unhandled promise rejection: Error The pattern "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.restart" is not a valid ID pattern
linux-control.0 2023-11-05 15:20:43.086	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
linux-control.0 2023-11-05 15:20:43.018	warn	Used invalid characters: linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.restart changed to linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by_x2duuid-9C29_x2d4D7D.restart
linux-control.0 2023-11-05 15:20:42.973	warn	State "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.description" has no existing object, this might lead to an error in future versions
linux-control.0 2023-11-05 15:20:42.971	warn	Used invalid characters: linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.description changed to linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by_x2duuid-9C29_x2d4D7D.description
linux-control.0 2023-11-05 15:20:42.967	warn	State "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.running" has no existing object, this might lead to an error in future versions
linux-control.0 2023-11-05 15:20:42.965	warn	Used invalid characters: linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.running changed to linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by_x2duuid-9C29_x2d4D7D.running
linux-control.0 2023-11-05 15:20:42.962	warn	State "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.active" has no existing object, this might lead to an error in future versions

linux-control.0 2023-11-05 15:20:42.958	warn	Used invalid characters: linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.active changed to linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by_x2duuid-9C29_x2d4D7D.active
linux-control.0 2023-11-05 15:20:42.916	warn	State "linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.load" has no existing object, this might lead to an error in future versions
linux-control.0 2023-11-05 15:20:42.913	warn	Used invalid characters: linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by\x2duuid-9C29\x2d4D7D.load changed to linux-control.0.Proxmox.services.systemd-fsck@dev-disk-by_x2duuid-9C29_x2d4D7D.load
```

**Comment by Negalein** [comment]
läuft jetzt, nachdem ich in den letzten Wochen bestimmt 20x neu installiert habe!
