### ISSUE TITLE
command not found bei cmdAptUpdate

### ISSUE THREAD

**Issue by Klaus-Lucas** [Scrounger/ioBroker.linux-control#60]
Nach dem Start des Adapters kommen solche Fehlermeldungen:
```
2023-12-19 12:36:40.526 - error: linux-control.0 (875761) [cmdAptUpdate] flosk (192.168.178.44:22): response error: bash: line 1: column: command not found, stack: ResponseError: [cmdAptUpdate] flosk (192.168.178.44:22): bash: line 1: column: command not found
at LinuxControl.sendCommand (/opt/iobroker/node_modules/iobroker.linux-control/main.js:886:26)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at LinuxControl.cmdAptUpdate (/opt/iobroker/node_modules/iobroker.linux-control/main.js:721:18)
at LinuxControl.updateInfos (/opt/iobroker/node_modules/iobroker.linux-control/main.js:621:5)
at LinuxControl.refreshHost (/opt/iobroker/node_modules/iobroker.linux-control/main.js:79:5)
at async Promise.allSettled (index 1)
at LinuxControl.onReady (/opt/iobroker/node_modules/iobroker.linux-control/main.js:53:4)
```

Update funktioniert:
```
klu@flosk:~$ sudo apt update
[sudo] password for klu:
Hit:1 http://de.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://de.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
klu@flosk:~$

klu@flosk:~$ sudo apt-get update
[sudo] password for klu:
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 http://de.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://de.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://de.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 https://dl.google.com/linux/chrome/deb stable InRelease
Fetched 110 kB in 0s (350 kB/s)
Reading package lists... Done
```

Meine Einstellungen:
![grafik](https://github.com/Scrounger/ioBroker.linux-control/assets/36620907/fa1b2197-e701-42af-8816-cb365b927d92)

![klu_031](https://github.com/Scrounger/ioBroker.linux-control/assets/36620907/b8413022-9072-44f6-af97-347b3d6055d8)

![klu_032](https://github.com/Scrounger/ioBroker.linux-control/assets/36620907/87c2395b-0f82-4265-813a-a3842201d263)

![klu_033](https://github.com/Scrounger/ioBroker.linux-control/assets/36620907/ec9cdd3f-460d-4380-873d-816e6b41ba41)

![klu_034](https://github.com/Scrounger/ioBroker.linux-control/assets/36620907/de798398-c8e0-479e-97cf-ff775784d318)

![klu_035](https://github.com/Scrounger/ioBroker.linux-control/assets/36620907/78ff868e-ed02-49a7-8071-37bd49b6e6ce)
![klu_036](https://github.com/Scrounger/ioBroker.linux-control/assets/36620907/ef7a747d-3d99-47a9-a4d8-8bae142ccfd0)

Fehler ist weg, wenn ich updates.all auf die Blacklist schiebe.

**Versions:**  
 - Adapter: 1.1.5
 - Admin: 6.12.9
 - js-controller: 5.0.17
 - Node.js: 18.19.0
 - NPM:  10.2.3
 - Operating system: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)

**Comment by Klaus-Lucas** [comment]
Problem gefunden:
This system has been minimized by removing packages and content that are
not required on a system that users do not log into.
To restore this content, you can run the 'unminimize' command.

unminimize abgesetzt, Problem weg.
